# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and deploy to gh-pages
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: set git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action for ${GITHUB_ACTOR}"
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm ci
        npm run build
    - name: checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        clean: false
    - name: clean up, copy generated files and commit
      run: |
        rm -f *.json *.html
        cp build/* .
        git commit -m "Rebuild after master commit\nRef #${GITHUB_SHA}" -A
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force: true
